# Tarea 1 · El conjunto de datos del proyecto

**Fundamentos de Ciencia de Datos e IA (CDIAG1003)** · Proyecto integrador · Deber del primer parcial · Trabajo en grupo · Entrega: inicio de la sesión 9

**Nombre del grupo:** Grupo x

**Integrantes:** _escriba aquí (nombres y apellidos)_ &nbsp;&nbsp; **Paralelo:** 2

Esta plantilla tiene las siete secciones que pide la tarea. Las celdas de código traen un ejemplo que funciona con `datos/ventas_sucio.csv` (el archivo de la sesión 7): **reemplácelo por el conjunto de datos del grupo** y adapte cada celda. El texto en cursiva son indicaciones: bórrelo al escribir sus respuestas.

La tarea combina lo visto en las sesiones 3 (tipos de datos, preguntas de negocio y KPIs), 5 (pandas: leer, inspeccionar y seleccionar; recolección de datos) y 7 (limpieza y preparación: duplicados, texto, tipos, faltantes, atípicos). La sección 5 sigue la lista de verificación del notebook de clase de la sesión 7.

Antes de entregar: *Kernel → Restart Kernel and Run All Cells*. El notebook debe ejecutarse de arriba abajo sin errores, con el archivo de datos en la carpeta `datos`.

## 1. Origen de los datos (10 puntos)

*Complete la tabla. Si los datos se obtuvieron con una API o con web scraping, incluya en la sección 2 el código que los obtuvo y guarde el resultado en un archivo, para no repetir la consulta.*

| | |
|---|---|
| **Nombre del conjunto de datos** |IMDb Top 1000 Movies |
| **Fuente** (institución, portal o sitio) |MDb Top 1000 Movies, conjunto de datos distribuido públicamente en Kaggle |
| **Enlace** | https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows?resource=download |
| **Fecha de descarga o de consulta** | 9 de octubre de 2026 |
| **Vía de obtención** (archivo, API o *web scraping*) |Archivo CSV descargado |
| **Licencia o permiso de uso** (por qué el grupo puede usar estos datos) | CC0: Dominio público (Public Domain), según la licencia indicada en la página de Kaggle del conjunto de datos. |
| **Quién recopiló los datos y con qué fin** |El conjunto de datos fue publicado en Kaggle por Harshit Shankhdhar y contiene información relacionada con IMDb. La página no especifica con detalle quién realizó la recolección original ni el procedimiento exacto utilizado. El conjunto de datos se presenta para realizar análisis exploratorios de películas y programas de televisión.  |
| **¿Contiene datos personales?** (si los contiene, cómo se protegen) |Contiene nombres de directores y actores, que son datos identificativos de carácter público y profesional. Sin embargo, no incluye datos privados de los usuarios que votaron |

## 2. Carga de los datos (10 puntos)

*Lea el archivo con los parámetros necesarios (`sep`, `encoding`, `decimal`, `sheet_name`…). Explique en una línea cada parámetro que tuvo que cambiar y por qué. No corrija nada todavía: la tabla original se guarda en `datos` y la limpieza se hace en la sección 5 sobre una copia.*

In [2]:
import numpy as np
import pandas as pd

RUTA = "../imdb_top_1000.csv"         # ← reemplace por el archivo del grupo

datos = pd.read_csv(RUTA)               # ← añada aquí los parámetros que su archivo necesite
datos.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

*Parámetros usados y motivo:* …

## 3. Tamaño y tipos (parte del diccionario de datos)

In [3]:
print("Filas y columnas:", datos.shape)
datos.dtypes

Filas y columnas: (1000, 16)

Poster_Link          str
Series_Title         str
Released_Year        str
Certificate          str
Runtime              str
Genre                str
IMDB_Rating      float64
Overview             str
Meta_score       float64
Director             str
Star1                str
Star2                str
Star3                str
Star4                str
No_of_Votes        int64
Gross                str
dtype: object

In [4]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 125.1 KB

## 4. Diccionario de datos (20 puntos)

*La celda siguiente genera un borrador con lo que pandas puede calcular. Con ese borrador, complete la tabla de abajo: una fila por columna. El «tipo de dato» es el de la sesión 3 (numérico discreto, numérico continuo, categórico nominal, categórico ordinal, fecha, texto libre, booleano), y no siempre coincide con el tipo de pandas: un código escrito con dígitos es categórico.*

In [5]:
borrador = pd.DataFrame({
    "tipo_pandas": datos.dtypes.astype(str),
    "valores_distintos": datos.nunique(),
    "faltantes": datos.isna().sum(),
    "ejemplo": datos.iloc[0],
})
borrador

,tipo_pandas,valores_distintos,faltantes,ejemplo
Poster_Link,str,1000,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...
Series_Title,str,999,0,The Shawshank Redemption
Released_Year,str,100,0,1994
Certificate,str,16,101,A
Runtime,str,140,0,142 min
Genre,str,202,0,Drama
IMDB_Rating,float64,17,0,9.3
Overview,str,1000,0,Two imprisoned men bond over a number of years...
Meta_score,float64,63,157,80.0
Director,str,548,0,Frank Darabont
Star1,str,660,0,Tim Robbins
Star2,str,841,0,Morgan Freeman
Star3,str,891,0,Bob Gunton
Star4,str,939,0,William Sadler
No_of_Votes,int64,999,0,2343110
Gross,str,823,169,"28,341,469"

In [6]:
datos.describe()          # mínimos, máximos y promedios de las columnas numéricas

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

| Columna | Tipo en pandas | Tipo de dato | Unidad | Valores posibles o rango | Qué significa |
|---|---|---|---|---|---|
|Released_Year | str | fecha | año | Años de estreno válidos, por ejemplo 1994 | Año en que se estrenó la película. |
|Runtime | str | numerica | minutos | Numeros Naturales, por ejemplo 142 | Duración de la película. |
|Gross | str | numerica | USD | Numeros Reales postivios, por ejemplo 28,341,469 | Recaudación de la película en dólares estadounidenses. |
| | | | | | |
| | | | | | |
| | | | | | |

*¿Alguna columna tiene un tipo en pandas que no corresponde a su tipo de dato (un número leído como texto, una fecha leída como texto, un código leído como número)? Indique cuál. La corrección se hace en la sección 5.4.*

## 5. Limpieza y preparación de los datos (35 puntos)

*Es la lista de verificación de la sesión 7, aplicada a su conjunto de datos. Trabaje sobre la copia `limpio`; `datos` queda como llegó. En cada paso: primero mida, después decida y escriba la decisión en la celda de texto, y al final ejecute el código. La limpieza no inventa datos: recupera la tabla que debió llegar.*

### 5.1 Diagnóstico (5 puntos)

*Antes de tocar un dato: ¿hay filas repetidas?, ¿columnas vacías?, ¿cuántos valores distintos tiene cada columna de texto y cuáles son variantes de un mismo valor (espacios, mayúsculas, abreviaturas, tildes)?*

In [7]:
print("Filas duplicadas exactas:", datos.duplicated().sum())
print("Columnas vacías:", datos.columns[datos.isna().all()].tolist())

texto = datos.select_dtypes(exclude="number").columns
pd.DataFrame({"valores_distintos": datos[texto].nunique(), "faltantes": datos[texto].isna().sum()})

Filas duplicadas exactas: 0
Columnas vacías: []

               valores_distintos  faltantes
Poster_Link                 1000          0
Series_Title                 999          0
Released_Year                100          0
Certificate                   16        101
Runtime                      140          0
Genre                        202          0
Overview                    1000          0
Director                     548          0
Star1                        660          0
Star2                        841          0
Star3                        891          0
Star4                        939          0
Gross                        823        169

In [8]:
datos["Certificate"].value_counts(dropna=False)
datos["Genre"].value_counts(dropna=False)

Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Action, Adventure, Family     1
Action, Crime, Mystery        1
Animation, Drama, Romance     1
Drama, War, Western           1
Adventure, Comedy, War        1
Name: count, Length: 202, dtype: int64

*Problemas encontrados (una línea por problema):* …

### 5.2 Duplicados y columnas vacías (5 puntos)

*Elimine las filas duplicadas exactas y las columnas totalmente vacías. Si su tabla no tiene identificador de fila, decida con el diccionario de datos si dos filas iguales pueden ser reales.*

In [10]:
limpio = datos.drop_duplicates().reset_index(drop=True)
vacias = limpio.columns[limpio.isna().all()].tolist()
limpio = limpio.drop(columns=vacias)

print("Filas eliminadas:", len(datos) - len(limpio), "| columnas eliminadas:", vacias)
limpio.shape

Filas eliminadas: 0 | columnas eliminadas: []

(1000, 16)

*Decisión:*Se eliminaron las filas duplicadas exactas y las columnas totalmente vacías. En este dataset no se encontraron filas duplicadas ni columnas completamente vacías, por lo que no se eliminó ningún registro ni ninguna columna. Se conservaron las 1000 filas y las 16 columnas originales.

### 5.3 Texto: espacios, mayúsculas y sinónimos (5 puntos)

*Una celda por columna de texto con variantes. El orden importa: espacios → caja → sinónimos (`replace`). Al final, cada columna debe tener una sola forma de escribir cada valor.*

In [11]:
limpio["Certificate"] = (limpio["Certificate"].str.strip().replace({"": pd.NA}))
limpio["Certificate"].value_counts(dropna=False)

Certificate
U           234
A           197
UA          175
R           146
NaN         101
PG-13        43
PG           37
Passed       34
G            12
Approved     11
TV-PG         3
GP            2
TV-14         1
16            1
TV-MA         1
Unrated       1
U/A           1
Name: count, dtype: int64

In [17]:
columnas_texto = [
    "Genre", "Director",
    "Star1", "Star2", "Star3", "Star4"
]

for col in columnas_texto:
    limpio[col] = limpio[col].str.strip()

limpio[columnas_texto].nunique()

Genre       202
Director    548
Star1       660
Star2       841
Star3       891
Star4       939
dtype: int64

*Decisión (qué variantes se unificaron y por qué): Se eliminaron los espacios sobrantes al inicio y al final de los valores de las columnas de texto, como Certificate, Genre, Director, Star1, Star2, Star3 y Star4. Se conservaron las mayúsculas, minúsculas y la escritura original de los títulos y nombres propios para evitar modificar información válida. No se reemplazaron sinónimos porque no se identificaron variantes que necesitaran unificarse.

### 5.4 Tipos: números y fechas (5 puntos)

*Convierta a número las columnas numéricas leídas como texto (`str.replace` para quitar símbolos, `pd.to_numeric(errors="coerce")`) y a fecha las columnas de fecha (`pd.to_datetime` con `format=`; un `to_datetime` por formato si hay varios). Compruebe después que `dtypes` muestra lo que dice el diccionario de datos.*

In [24]:

# 1. Año de estreno
limpio["Released_Year"] = pd.to_numeric(limpio["Released_Year"].astype("string").str.strip(),errors="coerce").astype("Int64")

# 2. Duración en minutos
limpio["Runtime"] = pd.to_numeric(limpio["Runtime"].astype("string").str.replace(" min", "", regex=False).str.strip(),errors="coerce").astype("Int64")

# 3. Recaudación en dólares
limpio["Gross"] = pd.to_numeric(limpio["Gross"].astype("string").str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip(),errors="coerce").astype("Int64")

print(limpio[["Released_Year", "Runtime", "Gross"]].dtypes)
print("\nValores faltantes:")
print(limpio[["Released_Year", "Runtime", "Gross"]].isna().sum())

Released_Year    Int64
Runtime          Int64
Gross            Int64
dtype: object

Valores faltantes:
Released_Year      1
Runtime            0
Gross            169
dtype: int64

*Columnas convertidas y motivo:* Released_Year: se convirtió de string a entero (Int64) porque representa el año de estreno de cada película. Los valores inválidos se transformaron en faltantes para evitar errores.

Runtime: se convirtió de string a entero (Int64) porque representa la duración en minutos. Se eliminó el texto " min" antes de la conversión.

Gross: se convirtió de string a entero (Int64) porque representa la recaudación en dólares estadounidenses. Se eliminaron las comas separadoras de miles y, si estaba presente, el símbolo $.

Se utilizó errors="coerce" para convertir los valores que no se pueden interpretar como números en valores faltantes (NA). Se conservaron las filas originales.

### 5.5 Datos faltantes (8 puntos)

*Cuente los faltantes por columna y como porcentaje. Para cada columna con faltantes, decida y justifique: recuperar el valor (de otras columnas o filas), categoría explícita («Sin dato»), mediana o media, eliminar la fila (solo si no sirve sin ese dato) o eliminar la columna (si casi toda falta).*

In [25]:

resumen_faltantes = pd.DataFrame({
    "faltantes": limpio.isna().sum(),
    "porcentaje": (limpio.isna().mean() * 100).round(1)
})

resumen_faltantes.sort_values(
    "faltantes",
    ascending=False
)

               faltantes  porcentaje
Gross                169        16.9
Meta_score           157        15.7
Certificate          101        10.1
Released_Year          1         0.1
Runtime                0         0.0
Genre                  0         0.0
Series_Title           0         0.0
Poster_Link            0         0.0
Overview               0         0.0
IMDB_Rating            0         0.0
Star1                  0         0.0
Director               0         0.0
Star2                  0         0.0
Star3                  0         0.0
Star4                  0         0.0
No_of_Votes            0         0.0

| Columna | Faltantes | Decisión | Por qué |
|---|---|---|---|
|Gross |169 |Na |No se puede conocer la recaudación exacta con seguridad a partir de otras columnas. |
|Meta_score |157 |Na |No se debe inventar una puntuación que no está registrada. |
|Certificate |101 |"sin dato" |Permite identificar que la clasificación no está disponible sin eliminar películas. |
|Released_Year |1 |Na |	El año no es válido o no se pudo convertir; no se debe adivinar. |

In [26]:
# Certificate: categoría explícita
limpio["Certificate"] = limpio["Certificate"].fillna("Sin dato")
# Gross, Meta_score y Released_Year se mantienen como faltantes

print(limpio.isna().sum())
print("Dimensiones finales:", limpio.shape)

Poster_Link        0
Series_Title       0
Released_Year      1
Certificate        0
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64
Dimensiones finales: (1000, 16)

### 5.6 Valores atípicos (4 puntos)

*Revise `describe()` y la regla IQR en las columnas numéricas. Corrija solo los errores evidentes (y documente la corrección); un valor extremo real se queda.*

In [27]:
limpio.describe()

,Released_Year,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross
count,999.0,1000.0,1000.000000,843.000000,1.000000e+03,831.0
mean,1991.217217,122.891,7.949300,77.971530,2.736929e+05,68034750.873646
std,23.297025,28.093671,0.275491,12.376099,3.273727e+05,109750043.192185
min,1920.0,45.0,7.600000,28.000000,2.508800e+04,1305.0
25%,1976.0,103.0,7.700000,70.000000,5.552625e+04,3253559.0
50%,1999.0,119.0,7.900000,79.000000,1.385485e+05,23530892.0
75%,2009.0,137.0,8.100000,87.000000,3.741612e+05,80750893.5
max,2020.0,321.0,9.300000,100.000000,2.343110e+06,936662225.0

In [29]:

columna = "Runtime"
q1, q3 = limpio[columna].quantile([0.25, 0.75])
iqr = q3 - q1
limite_inf = q1 - 1.5 * iqr
limite_sup = q3 + 1.5 * iqr
atipicos = limpio[(limpio[columna] < limite_inf) |(limpio[columna] > limite_sup)]

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Límite inferior:", limite_inf)
print("Límite superior:", limite_sup)
print("Cantidad de valores atípicos:", len(atipicos))

atipicos[["Series_Title", columna]].sort_values(
    columna, ascending=False
)

Q1: 103.0
Q3: 137.0
IQR: 34.0
Límite inferior: 52.0
Límite superior: 188.0
Cantidad de valores atípicos: 29

                                      Series_Title  Runtime
140                             Gangs of Wasseypur      321
812                                         Hamlet      242
314                             Gone with the Wind      238
71                     Once Upon a Time in America      229
116                             Lawrence of Arabia      228
247              Lagaan: Once Upon a Time in India      224
552                           The Ten Commandments      220
300                                        Ben-Hur      212
156                         Swades: We, the People      210
484                                   The Irishman      209
31                            Shichinin no samurai      207
290                                  Andrei Rublev      205
177                                         Sholay      204
820                                      Malcolm X      202
3                           The Godfather: Part II      202
5    The Lord of the Rings: The Return of the King      201
996                                          Giant      201
549                                      Spartacus      197
430                                 Doctor Zhivago      197
206                                     Kis Uykusu      196
7                                 Schindler's List      195
652                                        Titanic      194
686                                The Right Stuff      193
629                                     Veer-Zaara      192
411                                         Gandhi      191
400                                            JFK      189
25                                  The Green Mile      189
258                    Dilwale Dulhania Le Jayenge      189
194                                   Sherlock Jr.       45

In [30]:
limpio[["Series_Title", "Runtime"]].sort_values(
    "Runtime", ascending=False
).head(10)

                          Series_Title  Runtime
140                 Gangs of Wasseypur      321
812                             Hamlet      242
314                 Gone with the Wind      238
71         Once Upon a Time in America      229
116                 Lawrence of Arabia      228
247  Lagaan: Once Upon a Time in India      224
552               The Ten Commandments      220
300                            Ben-Hur      212
156             Swades: We, the People      210
484                       The Irishman      209

*Decisión (qué se corrigió, qué se dejó y por qué):* Se revisaron los valores extremos de las columnas numéricas mediante estadísticas descriptivas y la regla del rango intercuartílico (IQR). Se analizaron las películas con mayor duración, como *Gangs of Wasseypur* (321 minutos) y *Hamlet* (242 minutos). No se modificaron ni eliminaron estos valores, ya que no se confirmó que fueran errores. También se decidió conservar los valores extremos de `No_of_Votes`, `IMDB_Rating` y `Meta_score`, porque pueden representar datos reales importantes para el análisis de popularidad y calificaciones. No se realizaron correcciones de valores atípicos sin evidencia de error.

### 5.7 Verificación y archivo limpio (3 puntos)

*Compare la tabla antes y después. Un total conocido (o una cuenta que el grupo pueda comprobar en la fuente) debe coincidir. Guarde la tabla limpia en `datos/` con `to_csv(index=False)`: es la que se usará en el resto del proyecto.*

In [33]:
resumen = pd.DataFrame({
    "antes": [datos.shape[0], datos.shape[1], datos.duplicated().sum(), datos.isna().sum().sum()],
    "despues": [limpio.shape[0], limpio.shape[1], limpio.duplicated().sum(), limpio.isna().sum().sum()],
}, index=["filas", "columnas", "duplicados", "faltantes"])
resumen

            antes  despues
filas        1000     1000
columnas       16       16
duplicados      0        0
faltantes     427      327

In [37]:

# Comprobar una cantidad conocida de películas
print("Total de películas:", len(limpio))
print("Películas con número de votos:", limpio["No_of_Votes"].notna().sum())

# Guardar el dataset limpio
from pathlib import Path

carpeta_datos = Path("datos")
carpeta_datos.mkdir(exist_ok=True)

limpio.to_csv(carpeta_datos / "imdb_top_1000_limpio.csv", index=False)

print("Archivo limpio guardado en:", carpeta_datos / "../datos/imdb_top_1000_limpio.csv.")

Total de películas: 1000
Películas con número de votos: 1000
Archivo limpio guardado en: datos\..\datos\imdb_top_1000_limpio.csv.

*Comprobación (qué total se comparó y con qué):* Se verificó que el conjunto de datos original y el conjunto limpio conservaran las mismas 1000 filas y 16 columnas. Se comparó la cantidad de filas duplicadas, que fue 0 antes y después de la limpieza. También se compararon los valores faltantes, que disminuyeron de 427 a 327 después del tratamiento de los datos. Finalmente, se comprobó que la columna No_of_Votes, utilizada como indicador de popularidad, conservara los datos disponibles para el análisis.

## 6. Verificación de los requisitos del proyecto (5 puntos)

*La celda comprueba, sobre la tabla limpia, los requisitos de la ficha del proyecto. Indique en `columna_fecha_o_categorica` el nombre de la columna de fecha, o de la variable categórica con varias categorías, que permitirá comparar grupos o ver cambios en el tiempo.*

In [38]:
columna_fecha_o_categorica = "Released_Year"

n_filas, n_columnas = limpio.shape
numericas = limpio.select_dtypes(include="number").columns
no_numericas = [
    c for c in limpio.columns
    if c not in numericas
]

print("Al menos 1 000 filas:", n_filas >= 1000)
print("Al menos 6 columnas:", n_columnas >= 6)
print("Tiene columnas numéricas:", len(numericas) > 0)
print("Tiene columnas no numéricas:", len(no_numericas) > 0)
print(
    "Categorías o fechas distintas en",
    columna_fecha_o_categorica,
    ":",
    limpio[columna_fecha_o_categorica].nunique()
)

Al menos 1 000 filas: True
Al menos 6 columnas: True
Tiene columnas numéricas: True
Tiene columnas no numéricas: True
Categorías o fechas distintas en Released_Year : 99

*Conclusión: ¿el conjunto de datos cumple los requisitos? Si alguno no se cumple, ¿qué hará el grupo (ampliar el periodo, combinar archivos, cambiar de conjunto de datos)?*
El conjunto de datos de IMDb cumple los requisitos principales del proyecto, ya que contiene 1000 películas y 16 columnas, superando los mínimos de 1000 filas y 6 columnas.

*(El archivo de ejemplo `ventas_sucio.csv` no cumple el requisito de 1 000 filas: tiene 200 después de la limpieza.)*
Después de la limpieza, se conservaron las 1000 filas y las 16 columnas. Los valores faltantes que permanecen se documentaron y se tratarán según las necesidades de cada análisis

## 7. Tres selecciones y las preguntas del proyecto (20 puntos)

**7.1 Tres selecciones con sentido (10 puntos).** *Sobre la tabla limpia, escriba tres selecciones con `loc`, `iloc` o condiciones (sesión 5). Cada una debe responder una pregunta sencilla sobre los datos, escrita en una celda de texto antes del código, y terminar con una línea de interpretación.*

*Pregunta 1:* ¿Cuáles son las 5 películas mejor valoradas (con mayor IMDB_Rating) y cuáles son sus directores y años de estreno?

In [39]:
# selección 1
top_5_rating = limpio.sort_values(by="IMDB_Rating", ascending=False).loc[:, ["Series_Title", "Released_Year", "Director", "IMDB_Rating"]].iloc[:5]
top_5_rating

               Series_Title  Released_Year              Director  IMDB_Rating
0  The Shawshank Redemption           1994        Frank Darabont          9.3
1             The Godfather           1972  Francis Ford Coppola          9.2
2           The Dark Knight           2008     Christopher Nolan          9.0
3    The Godfather: Part II           1974  Francis Ford Coppola          9.0
4              12 Angry Men           1957          Sidney Lumet          9.0

*Interpretación:* Las 5 películas con la calificación más alta en la plataforma destacan por superar los 8.9 puntos de calificación IMDb, reflejando las producciones mejor evaluadas por el público en el dataset.

*Pregunta 2:* ¿Qué películas pertenecen al género de "Drama" y tienen más de 500,000 votos (No_of_Votes)?

In [40]:
# selección 2
drama_populares = limpio.loc[(limpio["Genre"].str.contains("Drama", na=False)) & (limpio["No_of_Votes"] > 500000), ["Series_Title", "Released_Year", "IMDB_Rating", "No_of_Votes"]]
drama_populares.head()

               Series_Title  Released_Year  IMDB_Rating  No_of_Votes
0  The Shawshank Redemption           1994          9.3      2343110
1             The Godfather           1972          9.2      1620367
2           The Dark Knight           2008          9.0      2303232
3    The Godfather: Part II           1974          9.0      1129952
4              12 Angry Men           1957          9.0       689845

*Interpretación:* La selección filtra las películas de Drama que han alcanzado una alta popularidad, permitiendo identificar los títulos del género dramático con mayor alcance e interacción de la audiencia.

*Pregunta 3:* ¿Cuáles son las primeras 10 películas en el conjunto de datos que fueron estrenadas a partir del año 2010?

In [41]:
# selección 3
recientes_pos2010 = limpio.loc[limpio["Released_Year"].astype(str) >= "2010", ["Series_Title", "Released_Year", "Genre", "IMDB_Rating"]].iloc[:10]
recientes_pos2010

,Series_Title,Released_Year,Genre,IMDB_Rating
8,Inception,2010,"Action, Adventure, Sci-Fi",8.8
18,Hamilton,2020,"Biography, Drama, History",8.6
19,Gisaengchung,2019,"Comedy, Drama, Thriller",8.6
20,Soorarai Pottru,2020,Drama,8.6
21,Interstellar,2014,"Adventure, Drama, Sci-Fi",8.6
33,Joker,2019,"Crime, Drama, Thriller",8.5
34,Whiplash,2014,"Drama, Music",8.5
35,The Intouchables,2011,"Biography, Comedy, Drama",8.5
53,Capharnaüm,2018,Drama,8.4
54,Ayla: The Daughter of War,2017,"Biography, Drama, History",8.4

*Interpretación:* Esta consulta permite aislar un bloque de producciones recientes (estrenadas de 2010 en adelante) para analizar la presencia del cine moderno dentro del Top 1000 de IMDb.

**7.2 Preguntas de negocio y KPIs, actualizados (10 puntos).** *Copie las tres preguntas de negocio y los dos KPIs de la ficha del grupo y ajústelos ahora que conoce las columnas: cada pregunta debe poder responderse con estos datos, y cada KPI debe tener una fórmula escrita con nombres de columnas reales.*

| | Texto | Columnas que se usarán |
|---|---|---|
| Pregunta 1 (descriptiva) |¿Cuáles son los géneros cinematográficos con mayor volumen de votos acumulados en la plataforma? |Genre, No_of_Votes |
| Pregunta 2 (diagnóstica) |¿Existe una relación directa entre el puntaje de la crítica (Meta_score) y la calificación dada por la audiencia (IMDB_Rating)? |Meta_score, IMDB_RatingS |
| Pregunta 3 |¿Cómo ha evolucionado el volumen promedio de votos de las películas a lo largo de las décadas de estreno? |Released_Year, No_of_Votes |
| KPI 1: nombre = fórmula (unidad) |(unidad)	Promedio de Popularidad por Película = Suma de votos totales / Número total de películas (votos) |No_of_Votes, Series_Title |
| KPI 2: nombre = fórmula (unidad) |Índice de Aprobación Crítica vs. Audiencia = (IMDB_Rating / 10) * (Meta_score / 100) * 100 (porcentaje %) |IMDB_Rating, Meta_score |

## Declaración

*Indique qué hizo cada integrante y qué ayudas se usaron (documentación, compañeros, herramientas de inteligencia artificial). Recuerde que la nota se pondera por el nivel oral: cualquier integrante debe poder explicar cualquier celda de este notebook.*
* **Diego Jahir Maldonado Zalamea:** Me encargó del desarrollo completo del contenido del cuaderno de trabajo (Jupyter Notebook), incluyendo la carga, limpieza, exploración, tratamiento de datos y formulación de preguntas de negocio, KPIs y selecciones con `loc`/`iloc`. Para optimizar la redacción, verificar la sintaxis en Python y estructurar los ejercicios,realizado con el apoyo de herramientas de inteligencia artificial (ChatGPT y Gemini).

* **Diego Tello:** Se encargó de la creacion del repositorio del proyecto en GitHub.

* **Ayudas utilizadas:** Documentación oficial de bibliotecas de Python (Pandas y NumPy), así como asistentes de IA (ChatGPT y Gemini) para la resolución de dudas, depuración de código y estructuración del reporte. Todos los integrantes del grupo comprenden y están capacitados para explicar la totalidad de las celdas desarrolladas en este notebook.